# Site settings
title: "Smatin"
email: "zhoucong50@gmail.com"
description: > # this means to ignore newlines until "baseurl:"
  记录认知
motto: "生活中有太多不幸，但是其中大部分都没有发生。"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zhco.github.io" # the base hostname & protocol for your site
twitter_username: smaatin
github_username:  zhco
weibo_id: "778940201"
weibo_name: "周大葱v"

# Build settings
markdown: kramdown
